kind: ConfigMap
apiVersion: v1
metadata:
  name: profile
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /home/user
data:
  .gitconfig: |
    [user]
          name = ${USER_NAME}
          email = ${USER_EMAIL}